### ISSUE TITLE
能不能Test4J的默认方法开始事务模式改一下呢

### ISSUE THREAD

**Issue by ChunxiYang** [test4j/test4j#2]
现在默认方法开启事务模式是Default（转换为Rollback）  导致不看你源码的人 测试插入数据的时候插入不到DB  能不能改一下默认为Disabled？

**Comment by ChunxiYang** [comment]
每次测试数据提交要显示事务模型
![image](https://cloud.githubusercontent.com/assets/13161775/14072347/11137f92-f4f2-11e5-873b-8e3fd812a8ac.png)

**Comment by tryternity** [comment]
在test4j.properties中可以设置全局事务模型
transactional.mode.default=rollback
transactional.mode.default=commit
transactional.mode.default=disabled

在 2016-03-28 14:34:04，"沐德" notifications@github.com 写道：

每次测试数据提交要显示事务模型

**Comment by tryternity** [comment]
在test4j.properties中可以设置全局事务模型
transactional.mode.default=rollback
transactional.mode.default=commit
transactional.mode.default=disabled

在 2016-03-28 14:29:51，"ChunxiYang" notifications@github.com 写道：

现在默认方法开启事务模式是Default（转换为Rollback） 导致不看你源码的人 测试插入数据的时候插入不到DB 能不能改一下默认为Disabled？

**Comment by linqyd** [comment]
我通过maven增加了test4j的dependency，但是每次运行测试都会报以下错误：
java.lang.NoClassDefFoundError: org/test4j/junit/Test4J

我用的是jdk 1.8。

请问是为什么？
