### ISSUE TITLE
如何从V2.0.7升级到V2.5

### ISSUE THREAD

**Issue by Razor0719** [test4j/test4j#7]
直接升级版本发现缺失许多依赖，V2.5目前还不能使用吗

**Comment by test4j** [comment]
没有办法平滑升级， 2.5直接使用了spring-test和spring-boot-test


| |
test4j
|
|
test4j@163.com
|
签名由网易邮箱大师定制


在2019年08月15日 10:42，Razor0719<notifications@github.com> 写道：

直接升级版本发现缺失许多依赖，V2.5目前还不能使用吗
